### ISSUE TITLE
Unhandled Promise rejection: No provider for BaseRequestOptions!

### ISSUE THREAD

**Issue by richardshergold** [sneas/ionic-native-http-connection-backend#2]
Hi

I'm having CORS issues with the WkWebView plugin and saw this solution so thought I'd give it a try.  I'm adding this to an existing project.  All I have done so far is add the files to my app.module.ts as per your instructions.  Is there anything else I need to do?

If I run my app on a device it now hangs with a white screen.  Running ionic serve I get the following errors:

```
polyfills.js:3 Unhandled Promise rejection: No provider for BaseRequestOptions! ; Zone: <root> ; Task: Promise.then ; Value: Error: No provider for BaseRequestOptions!
    at injectionError (vendor.js:1590)
    at noProviderError (vendor.js:1628)
    at ReflectiveInjector_._throwOrNull (vendor.js:3129)
    at ReflectiveInjector_._getByKeyDefault (vendor.js:3168)
    at ReflectiveInjector_._getByKey (vendor.js:3100)
    at ReflectiveInjector_.get (vendor.js:2969)
    at AppModuleInjector.createInternal (ng:///AppModule/module.ngfactory.js:457)
    at AppModuleInjector.NgModuleInjector.create (vendor.js:3917)
    at NgModuleFactory.create (vendor.js:3890)
    at vendor.js:5131 Error: No provider for BaseRequestOptions!
    at injectionError (http://localhost:8100/build/vendor.js:1590:86)
    at noProviderError (http://localhost:8100/build/vendor.js:1628:12)
    at ReflectiveInjector_._throwOrNull (http://localhost:8100/build/vendor.js:3129:19)
    at ReflectiveInjector_._getByKeyDefault (http://localhost:8100/build/vendor.js:3168:25)
    at ReflectiveInjector_._getByKey (http://localhost:8100/build/vendor.js:3100:25)
    at ReflectiveInjector_.get (http://localhost:8100/build/vendor.js:2969:21)
    at AppModuleInjector.createInternal (ng:///AppModule/module.ngfactory.js:457:75)
    at AppModuleInjector.NgModuleInjector.create (http://localhost:8100/build/vendor.js:3917:76)
    at NgModuleFactory.create (http://localhost:8100/build/vendor.js:3890:18)
    at http://localhost:8100/build/vendor.js:5131:61
n.onUnhandledError @ polyfills.js:3
polyfills.js:3 Error: Uncaught (in promise): Error: No provider for BaseRequestOptions!
Error: No provider for BaseRequestOptions!
    at injectionError (vendor.js:1590)
    at noProviderError (vendor.js:1628)
    at ReflectiveInjector_._throwOrNull (vendor.js:3129)
    at ReflectiveInjector_._getByKeyDefault (vendor.js:3168)
    at ReflectiveInjector_._getByKey (vendor.js:3100)
    at ReflectiveInjector_.get (vendor.js:2969)
    at AppModuleInjector.createInternal (ng:///AppModule/module.ngfactory.js:457)
    at AppModuleInjector.NgModuleInjector.create (vendor.js:3917)
    at NgModuleFactory.create (vendor.js:3890)
    at vendor.js:5131
    at injectionError (vendor.js:1590)
    at noProviderError (vendor.js:1628)
    at ReflectiveInjector_._throwOrNull (vendor.js:3129)
    at ReflectiveInjector_._getByKeyDefault (vendor.js:3168)
    at ReflectiveInjector_._getByKey (vendor.js:3100)
    at ReflectiveInjector_.get (vendor.js:2969)
    at AppModuleInjector.createInternal (ng:///AppModule/module.ngfactory.js:457)
    at AppModuleInjector.NgModuleInjector.create (vendor.js:3917)
    at NgModuleFactory.create (vendor.js:3890)
    at vendor.js:5131
    at c (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at o (polyfills.js:3)
    at <anonymous>
n.onUnhandledError @ polyfills.js:3
```

Anything else I need to do?  Are there things in my existing app that I need to change or should I just be able to add your lines of code to app.module.ts and it *should* magically work ?

many thanks for this!

**Comment by richardshergold** [comment]
If I change it to RequestOptions instead of BaseRequestOptions it works :-)

**Comment by sneas** [comment]
Thanks for the issue @richardshergold. Not sure how I missed that. On the project I'm working on we also use `RequestOptions`.
